import { ConfettiProvider } from "@/components/providers/confetti-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastProvider } from "@/components/providers/toast-provider";
import ProviderNext from "@/components/providers/next-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: any;
}) {
  return (
    <html data-theme="light" lang="en">
      <body className={inter.className}>
        <ConfettiProvider />
        <ToastProvider />
        <ProviderNext>{children}</ProviderNext>
      </body>
    </html>
  );
}
